CREATE TABLE BOARD(
	SEQ INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	TITLE VARCHAR(255) NOT NULL,
	CONTENT TEXT NOT NULL,
	REGDATE DATETIME NOT NULL
);

INSERT INTO BOARD(SEQ, TITLE, CONTENT, REGDATE)
SELECT IFNULL(MAX(SEQ),0)+1, '제목', '제목내용', SYSDATE() FROM BOARD;

INSERT INTO test.BOARD
(TITLE, CONTENT, REGDATE)
VALUES('제목2', '제목내용2', SYSDATE());

SELECT*
	FROM BOARD b;